name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
        - os: ubuntu-latest
          name: ubuntu
        - os: macos-latest
          name: macos
        - os: windows-latest
          name: windows
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.name }}
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - run: cmake -S . -B build
    - run: cmake --build build
    - run: ctest --verbose --build-config Debug
      working-directory: build/test
